import { Link } from "wouter";
import { ArrowLeft, FileText } from "lucide-react";
import { useI18n } from "@/i18n";
import { localizePath } from "@/lib/locale-paths";

type LegalSection = {
  title: string;
  body?: string[];
  bullets?: string[];
};

type LegalPageContent = {
  title: string;
  lastUpdated: string;
  intro: string;
  sections: LegalSection[];
};

const contactEmail = "Haitham.haj@gmail.com";

const termsContent: LegalPageContent = {
  title: "Terms of Service",
  lastUpdated: "May 2026",
  intro:
    "Welcome to INSPIRE Framework. These Terms of Service govern your access to and use of the INSPIRE Framework website and digital analysis product.",
  sections: [
    {
      title: "1. Product Description",
      body: [
        "INSPIRE Framework is a self-serve AI-powered digital analysis tool. Users complete an online assessment, and the system generates a structured operating profile report and copy-ready AI instructions based on the user's answers.",
      ],
    },
    {
      title: "2. Digital Product",
      body: ["INSPIRE Framework is delivered digitally through the website. No physical goods are shipped."],
    },
    {
      title: "3. No Professional Advice",
      body: [
        "The report and instructions generated by INSPIRE Framework are for informational, educational, and productivity purposes only. They do not constitute legal, medical, financial, psychological, or professional advice. Users are responsible for how they interpret and use the output.",
      ],
    },
    {
      title: "4. User Responsibility",
      body: [
        "Users are responsible for providing accurate and appropriate information when completing the assessment. The quality of the generated report depends on the information provided by the user.",
      ],
    },
    {
      title: "5. Payments",
      body: [
        "Payments are processed securely through Lemon Squeezy. INSPIRE Framework does not directly store full payment card details.",
      ],
    },
    {
      title: "6. Access and Delivery",
      body: [
        "After successful payment, users receive access to their digital analysis output through the website or related delivery flow. If a technical issue prevents access, users may contact support.",
      ],
    },
    {
      title: "7. Acceptable Use",
      body: [
        "Users may not misuse the website, attempt to bypass payment, reverse engineer the system, interfere with service operations, or use the product for unlawful purposes.",
      ],
    },
    {
      title: "8. Intellectual Property",
      body: [
        "The INSPIRE Framework concept, structure, website content, assessment flow, and generated formats are owned by the operator of INSPIRE Framework unless otherwise stated. Users may use their generated report and copy-ready instructions for their own personal or professional use.",
      ],
    },
    {
      title: "9. Changes to the Service",
      body: ["We may update, improve, or modify the service, pricing, features, or these Terms from time to time."],
    },
    {
      title: "10. Contact",
      body: ["For questions about these Terms, contact:", contactEmail],
    },
  ],
};

const privacyContent: LegalPageContent = {
  title: "Privacy Policy",
  lastUpdated: "May 2026",
  intro:
    "This Privacy Policy explains how INSPIRE Framework collects, uses, and protects information when you use our website and digital analysis product.",
  sections: [
    {
      title: "1. Information We Collect",
      body: ["We may collect:"],
      bullets: [
        "Name and email address",
        "Assessment answers submitted by the user",
        "Product usage and technical information",
        "Payment status and order information from Lemon Squeezy",
      ],
    },
    {
      title: "2. Payment Information",
      body: [
        "Payments are processed by Lemon Squeezy. We do not directly store full credit card numbers or sensitive payment card details.",
      ],
    },
    {
      title: "3. How We Use Information",
      body: ["We use collected information to:"],
      bullets: [
        "Generate the user's operating profile report",
        "Provide access to purchased digital products",
        "Improve the quality and reliability of the service",
        "Respond to support requests",
        "Maintain payment and order records",
      ],
    },
    {
      title: "4. AI-Generated Output",
      body: [
        "The user's assessment answers are used to generate a personalized digital report and copy-ready AI instructions. Users should avoid submitting sensitive personal information that is not necessary for the assessment.",
      ],
    },
    {
      title: "5. Sharing of Information",
      body: [
        "We do not sell personal information. We may share limited information with service providers required to operate the website, process payments, provide hosting, analytics, or support.",
      ],
    },
    {
      title: "6. Data Security",
      body: [
        "We take reasonable measures to protect user information. However, no online system can be guaranteed to be completely secure.",
      ],
    },
    {
      title: "7. Data Retention",
      body: [
        "We retain information as needed to provide the service, maintain records, comply with legal obligations, resolve disputes, and improve the product.",
      ],
    },
    {
      title: "8. User Requests",
      body: [
        "Users may contact us to request access, correction, or deletion of their information, subject to operational, legal, or security requirements.",
      ],
    },
    {
      title: "9. Contact",
      body: ["For privacy questions, contact:", contactEmail],
    },
  ],
};

const refundContent: LegalPageContent = {
  title: "Refund Policy",
  lastUpdated: "May 2026",
  intro:
    "INSPIRE Framework provides a self-serve digital analysis product that is generated based on the user's online assessment.",
  sections: [
    {
      title: "1. Digital Product Delivery",
      body: [
        "Because INSPIRE Framework is a digital product and the analysis may be generated or made available shortly after purchase, refunds are generally not available once the report or digital output has been delivered.",
      ],
    },
    {
      title: "2. Eligible Refund Cases",
      body: ["A refund may be considered in the following cases:"],
      bullets: [
        "Duplicate payment",
        "Accidental duplicate order",
        "Technical issue that prevents delivery of the purchased analysis",
        "Payment was successful but the user did not receive access to the purchased digital product",
      ],
    },
    {
      title: "3. Non-Refundable Cases",
      body: ["Refunds are generally not provided for:"],
      bullets: [
        "Change of mind after receiving the report",
        "Dissatisfaction based on personal preference after the digital output has been delivered",
        "Incorrect or incomplete answers submitted by the user",
        "Failure to use the generated instructions or report",
      ],
    },
    {
      title: "4. Refund Request Window",
      body: ["Refund requests must be submitted within 7 days of purchase."],
    },
    {
      title: "5. How to Request a Refund",
      body: ["To request a refund, contact:", contactEmail, "Please include:"],
      bullets: ["Order email", "Order number, if available", "Reason for the refund request"],
    },
    {
      title: "6. Payment Processor",
      body: [
        "Payments and refunds are processed through Lemon Squeezy. Approved refunds may take time to appear depending on the payment method and financial institution.",
      ],
    },
  ],
};

const termsContentAr: LegalPageContent = {
  title: "شروط الخدمة",
  lastUpdated: "مايو 2026",
  intro:
    "مرحباً بك في INSPIRE Framework. توضّح شروط الخدمة هذه قواعد الوصول إلى موقع INSPIRE Framework واستخدام المنتج الرقمي التحليلي المقدم من خلاله.",
  sections: [
    {
      title: "1. وصف المنتج",
      body: [
        "INSPIRE Framework هو أداة تحليل رقمية ذاتية مدعومة بالذكاء الاصطناعي. يقوم المستخدم بإكمال تقييم عبر الإنترنت، ثم ينشئ النظام تقريراً منظماً لملف التشغيل وتعليمات جاهزة للاستخدام مع الذكاء الاصطناعي بناءً على إجابات المستخدم.",
      ],
    },
    {
      title: "2. منتج رقمي",
      body: ["يتم تقديم INSPIRE Framework رقمياً من خلال الموقع. لا يتم شحن أو تسليم أي منتجات مادية."],
    },
    {
      title: "3. عدم تقديم مشورة مهنية",
      body: [
        "التقارير والتعليمات التي ينتجها INSPIRE Framework مخصصة لأغراض معلوماتية وتعليمية وإنتاجية فقط. لا تُعد هذه المخرجات مشورة قانونية أو طبية أو مالية أو نفسية أو مهنية. يتحمل المستخدم مسؤولية تفسير المخرجات واستخدامها.",
      ],
    },
    {
      title: "4. مسؤولية المستخدم",
      body: [
        "يتحمل المستخدم مسؤولية تقديم معلومات دقيقة ومناسبة عند إكمال التقييم. تعتمد جودة التقرير الناتج على المعلومات والإجابات التي يقدمها المستخدم.",
      ],
    },
    {
      title: "5. المدفوعات",
      body: [
        "تتم معالجة المدفوعات بشكل آمن عبر Lemon Squeezy. لا يقوم INSPIRE Framework بتخزين بيانات بطاقة الدفع الكاملة مباشرة.",
      ],
    },
    {
      title: "6. الوصول والتسليم",
      body: [
        "بعد إتمام الدفع بنجاح، يحصل المستخدم على الوصول إلى المخرجات الرقمية من خلال الموقع أو مسار التسليم المرتبط. في حال حدوث مشكلة تقنية تمنع الوصول، يمكن للمستخدم التواصل مع الدعم.",
      ],
    },
    {
      title: "7. الاستخدام المقبول",
      body: [
        "لا يجوز للمستخدم إساءة استخدام الموقع، أو محاولة تجاوز الدفع، أو الهندسة العكسية للنظام، أو تعطيل تشغيل الخدمة، أو استخدام المنتج لأغراض غير قانونية.",
      ],
    },
    {
      title: "8. الملكية الفكرية",
      body: [
        "تعود ملكية مفهوم INSPIRE Framework وبنيته ومحتوى الموقع ومسار التقييم وصيغ المخرجات إلى مشغّل INSPIRE Framework ما لم يُذكر خلاف ذلك. يجوز للمستخدم استخدام تقريره وتعليماته الجاهزة للنسخ لأغراضه الشخصية أو المهنية.",
      ],
    },
    {
      title: "9. التغييرات على الخدمة",
      body: ["يجوز لنا تحديث أو تحسين أو تعديل الخدمة أو الأسعار أو الميزات أو شروط الخدمة هذه من وقت لآخر."],
    },
    {
      title: "10. التواصل",
      body: ["للاستفسارات المتعلقة بهذه الشروط، يرجى التواصل عبر:", contactEmail],
    },
  ],
};

const privacyContentAr: LegalPageContent = {
  title: "سياسة الخصوصية",
  lastUpdated: "مايو 2026",
  intro:
    "توضح سياسة الخصوصية هذه كيفية جمع INSPIRE Framework للمعلومات واستخدامها وحمايتها عند استخدام الموقع والمنتج الرقمي التحليلي.",
  sections: [
    {
      title: "1. المعلومات التي نجمعها",
      body: ["قد نقوم بجمع المعلومات التالية:"],
      bullets: [
        "الاسم وعنوان البريد الإلكتروني",
        "إجابات التقييم التي يقدمها المستخدم",
        "معلومات الاستخدام والمعلومات التقنية المتعلقة بالمنتج",
        "حالة الدفع ومعلومات الطلب الواردة من Lemon Squeezy",
      ],
    },
    {
      title: "2. معلومات الدفع",
      body: [
        "تتم معالجة المدفوعات عبر Lemon Squeezy. نحن لا نخزن مباشرة أرقام بطاقات الائتمان الكاملة أو بيانات بطاقات الدفع الحساسة.",
      ],
    },
    {
      title: "3. كيفية استخدام المعلومات",
      body: ["نستخدم المعلومات التي يتم جمعها من أجل:"],
      bullets: [
        "إنشاء تقرير ملف التشغيل الخاص بالمستخدم",
        "توفير الوصول إلى المنتجات الرقمية المشتراة",
        "تحسين جودة الخدمة وموثوقيتها",
        "الرد على طلبات الدعم",
        "الاحتفاظ بسجلات الدفع والطلبات",
      ],
    },
    {
      title: "4. المخرجات المنشأة بالذكاء الاصطناعي",
      body: [
        "تُستخدم إجابات المستخدم في التقييم لإنشاء تقرير رقمي مخصص وتعليمات جاهزة للاستخدام مع الذكاء الاصطناعي. يُنصح المستخدم بتجنب إدخال معلومات شخصية حساسة لا تكون ضرورية للتقييم.",
      ],
    },
    {
      title: "5. مشاركة المعلومات",
      body: [
        "لا نبيع المعلومات الشخصية. قد نشارك معلومات محدودة مع مزودي الخدمات اللازمين لتشغيل الموقع، ومعالجة المدفوعات، وتقديم الاستضافة، والتحليلات، أو الدعم.",
      ],
    },
    {
      title: "6. أمن البيانات",
      body: [
        "نتخذ إجراءات معقولة لحماية معلومات المستخدم. ومع ذلك، لا يمكن ضمان أن أي نظام متصل بالإنترنت آمن بشكل كامل في جميع الظروف.",
      ],
    },
    {
      title: "7. الاحتفاظ بالبيانات",
      body: [
        "نحتفظ بالمعلومات حسب الحاجة لتقديم الخدمة، والاحتفاظ بالسجلات، والامتثال للالتزامات القانونية، وحل النزاعات، وتحسين المنتج.",
      ],
    },
    {
      title: "8. طلبات المستخدم",
      body: [
        "يمكن للمستخدم التواصل معنا لطلب الوصول إلى معلوماته أو تصحيحها أو حذفها، وذلك وفقاً للمتطلبات التشغيلية أو القانونية أو الأمنية ذات الصلة.",
      ],
    },
    {
      title: "9. التواصل",
      body: ["للاستفسارات المتعلقة بالخصوصية، يرجى التواصل عبر:", contactEmail],
    },
  ],
};

const refundContentAr: LegalPageContent = {
  title: "سياسة الاسترداد",
  lastUpdated: "مايو 2026",
  intro:
    "يوفر INSPIRE Framework منتجاً رقمياً تحليلياً ذاتياً يتم إنشاؤه بناءً على تقييم المستخدم عبر الإنترنت.",
  sections: [
    {
      title: "1. تسليم المنتج الرقمي",
      body: [
        "نظراً لأن INSPIRE Framework منتج رقمي وقد يتم إنشاء التحليل أو إتاحته بعد الشراء بوقت قصير، فإن عمليات الاسترداد لا تكون متاحة عادةً بعد تسليم التقرير أو المخرجات الرقمية.",
      ],
    },
    {
      title: "2. الحالات المؤهلة للاسترداد",
      body: ["يمكن النظر في طلب الاسترداد في الحالات التالية:"],
      bullets: [
        "دفع مكرر",
        "طلب مكرر عن طريق الخطأ",
        "مشكلة تقنية تمنع تسليم التحليل المشترى",
        "نجاح عملية الدفع دون حصول المستخدم على الوصول إلى المنتج الرقمي المشترى",
      ],
    },
    {
      title: "3. الحالات غير القابلة للاسترداد",
      body: ["لا يتم عادةً تقديم الاسترداد في الحالات التالية:"],
      bullets: [
        "تغيير الرأي بعد استلام التقرير",
        "عدم الرضا بناءً على تفضيل شخصي بعد تسليم المخرجات الرقمية",
        "تقديم إجابات غير صحيحة أو غير مكتملة من قبل المستخدم",
        "عدم استخدام التعليمات أو التقرير الناتج",
      ],
    },
    {
      title: "4. مدة طلب الاسترداد",
      body: ["يجب تقديم طلبات الاسترداد خلال 7 أيام من تاريخ الشراء."],
    },
    {
      title: "5. كيفية طلب الاسترداد",
      body: ["لطلب الاسترداد، يرجى التواصل عبر:", contactEmail, "يرجى تضمين المعلومات التالية:"],
      bullets: ["البريد الإلكتروني المستخدم في الطلب", "رقم الطلب إن وجد", "سبب طلب الاسترداد"],
    },
    {
      title: "6. معالج الدفع",
      body: [
        "تتم معالجة المدفوعات وعمليات الاسترداد عبر Lemon Squeezy. قد تستغرق عمليات الاسترداد المعتمدة بعض الوقت حتى تظهر، وذلك بحسب وسيلة الدفع والمؤسسة المالية.",
      ],
    },
  ],
};

function LegalPage({ content }: { content: LegalPageContent }) {
  const { locale, dir } = useI18n();
  const isAr = locale === "ar";

  return (
    <div className="min-h-screen bg-[#070817] px-4 py-12 text-slate-100 sm:px-6 lg:px-8" dir={dir}>
      <div className="mx-auto max-w-3xl">
        <Link
          href={localizePath("/", locale)}
          className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-slate-400 transition-colors hover:text-rose-200"
        >
          <ArrowLeft className={`h-4 w-4 ${isAr ? "rotate-180" : ""}`} />
          {isAr ? "العودة إلى INSPIRE" : "Back to INSPIRE"}
        </Link>

        <header className="mb-10 border-b border-slate-400/10 pb-8">
          <div className="mb-5 inline-flex h-12 w-12 items-center justify-center rounded-2xl border border-rose-300/20 bg-rose-500/[0.08] text-rose-200">
            <FileText className="h-6 w-6" />
          </div>
          <h1 className="font-display text-4xl font-black tracking-tight text-white sm:text-5xl">
            {content.title}
          </h1>
          <p className={`mt-3 text-sm font-bold text-rose-200/80 ${isAr ? "" : "uppercase tracking-[0.18em]"}`}>
            {isAr ? "آخر تحديث:" : "Last updated:"} {content.lastUpdated}
          </p>
          <p className="mt-6 text-base leading-8 text-slate-300">{content.intro}</p>
        </header>

        <div className="space-y-8">
          {content.sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-xl font-black text-slate-100">{section.title}</h2>
              {section.body?.map((paragraph) => (
                <p key={paragraph} className="mt-3 text-[15px] leading-7 text-slate-300">
                  {paragraph}
                </p>
              ))}
              {section.bullets && (
                <ul
                  className={`mt-3 list-disc space-y-2 text-[15px] leading-7 text-slate-300 ${
                    isAr ? "pr-5" : "pl-5"
                  }`}
                >
                  {section.bullets.map((bullet) => (
                    <li key={bullet}>{bullet}</li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}

export function TermsPage() {
  const { locale } = useI18n();
  return <LegalPage content={locale === "ar" ? termsContentAr : termsContent} />;
}

export function PrivacyPage() {
  const { locale } = useI18n();
  return <LegalPage content={locale === "ar" ? privacyContentAr : privacyContent} />;
}

export function RefundPolicyPage() {
  const { locale } = useI18n();
  return <LegalPage content={locale === "ar" ? refundContentAr : refundContent} />;
}
