import type { Dictionary } from "./ar";

export const en: Dictionary = {
  common: {
    languageSwitcher: {
      ar: "العربية",
      en: "English",
      label: "Language",
    },
    copy: {
      label: "Copy",
      copied: "Copied",
    },
    actions: {
      back: "Back",
      next: "Next",
      close: "Close",
      learnMore: "Learn more",
    },
    direction: {
      isRtl: "Arabic (right-to-left)",
      isLtr: "English (left-to-right)",
    },
    nav: {
      brandTagline: "Personal AI Instructions",
      myReports: "My reports",
      logout: "Log out",
      login: "Log in",
      startAssessment: "Start assessment",
    },
  },
  results: {
    pageTitle: "Your assistant operating profile",
    mismatchNotice:
      "The interface language differs from the report language. The report is shown in its original language to preserve its content.",
    dateLocale: "en-US",
    sections: {
      identity: "Assistant identity",
      benefits: "What you gain",
      roles: "Dynamic roles",
      modes: "Thinking modes",
      redLines: "Red lines",
      profile: "Full operating profile",
      howToUse: "How to use it",
      starters: "Starter prompts",
    },
    actions: {
      copyAll: "Copy assistant instructions",
      copySection: "Copy this section",
      share: "Share",
      downloadPdf: "Download PDF",
      openInChatGPT: "Open in ChatGPT",
      openInGemini: "Open in Gemini",
      openInClaude: "Open in Claude",
    },
    platforms: {
      chatgpt: {
        name: "ChatGPT",
        howTo:
          "Open ChatGPT customization settings and paste this profile into the instructions field to activate your assistant's working style.",
        step1: "Open ChatGPT and go to Customize ChatGPT settings.",
        step2:
          'Paste the operating profile into the "How would you like ChatGPT to respond?" field.',
        step3:
          "Save the settings. Your assistant will use this style in every new conversation.",
      },
      gemini: {
        name: "Gemini",
        howTo:
          "Open Gemini Gems or your personal context settings and paste this profile to apply the instructions to your conversations.",
        step1: 'Open Gemini and pick "Gems" to create a new assistant.',
        step2:
          'Paste the operating profile into the Gem instructions field and save it as "Project Assistant".',
        step3: "Open this Gem whenever you need this specific role.",
      },
      claude: {
        name: "Claude",
        howTo:
          "Open Claude Projects, create a new project, then paste this profile into the System Prompt to get the same behavior.",
        step1: "In Claude, create a new Project named after your project.",
        step2:
          "Paste the operating profile into the project's Custom Instructions field.",
        step3:
          "Start every conversation from this project to get the same consistent behavior.",
      },
    },
    starters: {
      eyebrow: "Start now",
      title: "Ready-to-use starter prompts",
      subtitle:
        "Copy any of these and paste it after the operating profile in any new conversation.",
      hint: "Use it directly in your preferred tool.",
    },
    status: {
      ready: "Your operating profile is ready",
      processingTitle: "Analyzing your behavioral profile",
      processingLine1:
        "The AI is generating your customized assistant instructions",
      processingLine2: "This usually takes 30–60 seconds",
      errorTitle: "Couldn't open the report",
      errorMissing: "Report not found",
      errorBack: "Back to my reports",
    },
    header: {
      titlePrefix: "Your assistant operating profile is ready",
      titleConnector: "for",
      subtitle:
        "Use it with ChatGPT, Gemini, or Claude so the AI works with you more clearly and consistently.",
      ctaPrimary: "Copy assistant instructions",
      ctaPrimarySuccess: "All instructions copied",
      ctaSecondary: "How do I use it?",
      generatedBy: "Generated by",
      myAssessments: "My reports",
      downloadPdf: "Download PDF",
      generatePdf: "Generate PDF",
      generatingPdf: "Generating...",
      share: "Share results",
      sharing: "Preparing...",
      revokeShare: "Revoke share",
      revoking: "Revoking...",
      linkCopiedPrefix: "Link copied:",
      shareCancelled: "Share link revoked",
    },
    identity: {
      eyebrow: "Your assistant identity",
      titlePrefix: "Your personal assistant ·",
      fallbackParagraph:
        "A custom operating profile has been built for your project. Use it so the assistant always works in your context instead of giving generic answers.",
      tagPartner: "Execution partner",
      tagReviewer: "Decision reviewer",
      tagContextAware: "Context-aware",
      tagOutcomeFocused: "Outcome-focused",
    },
    strengths: {
      eyebrow: "Your strengths",
      title: "What your assistant does especially well",
      subtitle:
        "These are the strengths the analysis identified in your style.",
    },
    redLines: {
      eyebrow: "Red lines",
      title: "What your assistant should avoid",
      subtitle:
        "Clear boundaries so outputs stay aligned with your style and project requirements.",
    },
    developmentAreas: {
      eyebrow: "Worth your attention",
      title: "Aspects to keep in mind",
      subtitle:
        "Not flaws — just areas worth noticing while working with the assistant.",
    },
    recommendations: {
      eyebrow: "Practical recommendations",
      title: "Steps you can start with",
      subtitle: "Recommendations tied to your style and intended outcomes.",
    },
    profile: {
      eyebrow: "Operating profile",
      title: "Your ready-to-use assistant instructions",
      subtitle:
        "An operating profile written in natural language, ready to paste into ChatGPT, Gemini, or Claude.",
      headerLabel: "Your assistant operating profile",
      headerHint: "Copy the instructions into ChatGPT / Gemini / Claude",
      copyAll: "Copy the full profile",
      copyAllSuccess: "Full profile copied",
    },
    howToUse: {
      eyebrow: "How to use it",
      title: "Where to use the operating profile",
      subtitle:
        "The same profile works across the three major tools. Pick yours and follow the steps.",
      headingPrefix: "How to use it in",
    },
    newCta: {
      line: "Want an operating profile for another project?",
      button: "Start a new assessment",
    },
    projectGoalLabel: "Project goal",
  },
  landing: {
    hero: {
      eyebrow: "Next Step AI · Human Interactive AI",
      headlineLead: "Your next step with",
      headlineAccent1: "AI",
      headlineMid: "begins when it understands",
      headlineAccent2: "how to work with you",
      paragraph:
        "INSPIRE builds a purpose-specific AI Operating Profile so ChatGPT, Gemini, and Claude understand your goal, style, and context from the very first message.",
      primaryCta: "Build your assistant profile",
      secondaryCta: "See how it works",
      trustLine: "Works with",
      slogan: "Every goal has its own INSPIRE",
      goalsEyebrow: "Pick your goal",
      goalsTitle: "Every goal has its own INSPIRE",
      goalsSubtitle:
        "Tap any goal to see how the operating profile adapts to serve it — different identity, roles, and thinking modes.",
      autoCycling: "Auto-cycling…",
      manualSelected: "Manually selected",
      profile: {
        liveLabel: "Assistant operating profile",
        tag: "INSPIRE Profile",
        identity: "Assistant identity",
        roles: "Dynamic roles",
        modes: "Thinking modes",
        rules: "Output rules",
        starter: "Starter prompt",
      },
      compare: {
        eyebrow: "Difference at a glance",
        title: "Same question — a closer answer",
        goalExampleLabel: "Goal example:",
        withoutLabel: "Without an operating profile",
        withoutTag: "Generic reply",
        withoutNote: "Less tied to your goal and context",
        withLabel: "With an INSPIRE operating profile",
        withTag: "Tailored reply",
        withChip1: "Contextual",
        withChip2: "Role-aware",
        withChip3: "Structured",
        withChip4: "Actionable",
      },
      goals: {
        pm: {
          label: "Project management",
          identityTitle: "Project management assistant",
          identityLine:
            "An execution partner that turns ideas into plans, surfaces risks, and orders priorities.",
          signal1: "Goal",
          signal2: "Priorities",
          signal3: "Phased plan",
          signal4: "Risk scan",
          role1: "Planning partner",
          role2: "Risk reviewer",
          role3: "Execution organizer",
          mode1: "Systematic thinking",
          mode2: "Priority analysis",
          mode3: "Decisive call",
          outputRule: "Numbered plan + risks + a clear next step",
          starter: "Help me turn this idea into a 3-phase execution plan…",
          before: "Generic time-management tips with no link to your project.",
          after:
            "A 3-phase plan, ordered risks, and a specific next step for your project.",
        },
        writing: {
          label: "Writing",
          identityTitle: "Writing assistant",
          identityLine:
            "A smart editor that protects your voice, suggests alternatives, and turns drafts into clearer prose.",
          signal1: "Tone of voice",
          signal2: "Reader audience",
          signal3: "Text structure",
          signal4: "Smart editing",
          role1: "Language editor",
          role2: "Alternative-line writer",
          role3: "Structure reviewer",
          mode1: "Narrative thinking",
          mode2: "Stylistic analysis",
          mode3: "Rephrasing",
          outputRule: "Clean draft + short alternatives + edit notes",
          starter: "Edit this paragraph while keeping my voice…",
          before: "Generic rewrite that may lose your original voice.",
          after:
            "Edits that preserve your voice, plus 2–3 alternatives and notes on rhythm.",
        },
        teaching: {
          label: "Teaching & training",
          identityTitle: "Teaching & training assistant",
          identityLine:
            "An instructional guide that simplifies concepts, gives examples, and builds graduated exercises.",
          signal1: "Learner level",
          signal2: "Real examples",
          signal3: "Graduated drills",
          signal4: "Plain explanation",
          role1: "Concept simplifier",
          role2: "Exercise designer",
          role3: "Comprehension checker",
          mode1: "Instructional thinking",
          mode2: "Close analogy",
          mode3: "Difficulty ramp",
          outputRule: "Plain explanation + example + short exercise",
          starter: "Explain this concept with a daily example, then quiz me…",
          before: "A long academic definition with no application.",
          after:
            "An explanation with a daily example, then a short exercise to gauge understanding.",
        },
        creative: {
          label: "Creative work",
          identityTitle: "Creative assistant",
          identityLine:
            "An ideas partner that generates alternatives, opens fresh angles, and offers constructive critique.",
          signal1: "Fresh angles",
          signal2: "Multiple options",
          signal3: "Constructive critique",
          signal4: "Challenge assumptions",
          role1: "Idea generator",
          role2: "Creative critic",
          role3: "Assumption-breaker",
          mode1: "Divergent thinking",
          mode2: "Unexpected linking",
          mode3: "Gentle critique",
          outputRule: "3 distinct alternatives + a critical note for each",
          starter: "Give me 3 different angles on this idea, then critique them…",
          before: "A single, predictable suggestion close to the obvious.",
          after:
            "3 alternatives from different angles, with constructive critique for each.",
        },
        business: {
          label: "Business decisions",
          identityTitle: "Business decisions assistant",
          identityLine:
            "A decision analyst that compares options, surfaces trade-offs, and recommends a justified choice.",
          signal1: "Compare options",
          signal2: "Trade-offs",
          signal3: "Decision risks",
          signal4: "Time horizon",
          role1: "Comparative analyst",
          role2: "Trade-off surfacer",
          role3: "Decision recommender",
          mode1: "Analytical thinking",
          mode2: "Criteria weighting",
          mode3: "Justified decision",
          outputRule: "Comparison table + trade-offs + a clear recommendation",
          starter: "Compare these two options against my criteria, then recommend…",
          before: "A general list of pros and cons with no preference.",
          after:
            "A comparison against your criteria, explicit trade-offs, and a justified recommendation.",
        },
      },
    },
    philosophy: {
      eyebrow: "The philosophy",
      title: "Why doesn't AI give you what you want?",
      subtitle:
        "It's not the tool. It's that the tool doesn't know who you are. Every person has a unique behavioral pattern in how they think, learn, and work — yet most AI instructions are written as if everyone were the same.",
      withoutTitle: "Without INSPIRE",
      withTitle: "With INSPIRE",
      before: [
        "You write a prompt and hope for the best",
        "You get generic answers that don't fit you",
        "You rephrase over and over without clarity",
        "AI offers options that don't match your style",
        "Time wasted re-explaining what you want every time",
      ],
      after: [
        "AI knows your style before you start",
        "Replies tailored to exactly how you think",
        "No re-explaining — just instant results",
        "AI challenges you instead of just agreeing",
        "Saves hours of repetition every week",
      ],
    },
    axes: {
      eyebrow: "The seven axes",
      titleSuffix: "— seven dimensions that define you",
      subtitle:
        "Each letter represents a behavioral dimension the system analyzes to build your unique profile",
      items: {
        intention: {
          name: "Intention",
          desc: "What truly drives you? Are you outcome-driven or process-driven? This axis reveals your real inner motivation.",
        },
        narrative: {
          name: "Narrative",
          desc: "How do you frame information? Stories and examples, or raw data and facts?",
        },
        style: {
          name: "Style",
          desc: "Methodical or spontaneous? Do you prefer clear structures or freedom to think?",
        },
        preferences: {
          name: "Preferences",
          desc: "What makes you comfortable — and what frustrates you — when working with AI? Your red lines and triggers.",
        },
        interaction: {
          name: "Interaction",
          desc: "How do you engage in real time? Do you prefer back-and-forth dialogue or direct responses?",
        },
        reflection: {
          name: "Reflection",
          desc: "How deep is your analytical thinking? Do you review and infer, or look for instant answers?",
        },
        evaluation: {
          name: "Evaluation",
          desc: "How do you measure success? By quantitative metrics or by qualitative feel and impact?",
        },
      },
      ctaTitle: "Discover your full profile",
      ctaSubtitle: "What do your scores look like across each axis? The assessment tells you.",
      ctaButton: "Start the free assessment",
    },
    sample: {
      eyebrow: "The actual output",
      title: "What do you get after the assessment?",
      subtitle: "A complete system prompt ready to paste into any AI model",
      features: [
        { title: "7-axis score sheet", desc: "Precise scores for each axis with qualitative interpretation" },
        { title: "Behavioral role analysis", desc: "Who you are specifically in the context of working with AI" },
        { title: "Your red lines", desc: "What you can't tolerate — defined precisely" },
        { title: "Comprehensive system prompt", desc: "500–800 words ready to paste into ChatGPT/Claude" },
        { title: "5 instant starter prompts", desc: "Prompts tailored to your project and style" },
        { title: "Downloadable PDF report", desc: "Easy to share with your team" },
      ],
      fileName: "system_prompt.txt",
      copyLabel: "Copy",
      copiedLabel: "Copied ✓",
      footerHint: "Paste this directly → ChatGPT / Claude / Gemini",
      badge: "System Prompt",
    },
    how: {
      eyebrow: "The process",
      title: "Three simple steps",
      subtitle: "From assessment to your personal AI instructions in under 20 minutes",
      steps: [
        {
          n: "1",
          title: "Take the assessment",
          desc: "24 behavioral questions + 8 AI scenarios that surface your real patterns",
        },
        {
          n: "2",
          title: "INSPIRE analyzes your pattern",
          desc: "7 axes analyzed in depth, building your unique signature into a comprehensive map",
        },
        {
          n: "3",
          title: "Get your instructions",
          desc: "Ready-to-use system prompt + PDF report + starter prompts for your project",
        },
      ],
    },
    pricing: {
      eyebrow: "Pricing",
      title: "Simple and transparent",
      subtitle: "Start free and upgrade when you're ready",
      free: {
        badge: "Quick assessment",
        price: "$0",
        period: "Free forever",
        cta: "Start for free",
        features: [
          "Free quick assessment (5 minutes)",
          "Instant starter prompts",
          "Intro to the seven axes",
          "No credit card",
        ],
      },
      paid: {
        ribbon: "One-time payment only",
        badge: "Full assessment",
        price: "$10",
        perUnit: "/ assessment",
        sublabel: "One-time payment · No subscription",
        cta: "Start the full assessment",
        features: [
          "Full personal assessment for any project",
          "INSPIRE 7-axis score sheet",
          "Ready-to-copy system prompt",
          "Downloadable professional PDF report",
          "Share results with your team",
          "Tailored instant starter prompts",
        ],
      },
    },
    faq: {
      eyebrow: "FAQ",
      title: "Questions & answers",
      items: [
        {
          q: "What is the INSPIRE framework?",
          a: "INSPIRE is a 7-axis behavioral analysis system (Intention, Narrative, Style, Preferences, Interaction, Reflection, Evaluation) designed to improve how you work with AI tools. Instead of using AI randomly, INSPIRE gives you instructions tailored to who you are.",
        },
        {
          q: "How long does the full assessment take?",
          a: "The full assessment takes 15–20 minutes and includes 24 behavioral questions, 8 interactive scenarios, and an open-ended question. The quick version takes only 5 minutes and generates instant starter prompts.",
        },
        {
          q: "What exactly does the assessment generate?",
          a: "The full assessment generates: a 7-axis INSPIRE score sheet, a professional role analysis, your red lines when working with AI, your behavioral strengths, growth areas, practical recommendations, a comprehensive system prompt you can paste into ChatGPT or Claude, and ready-to-use starter prompts.",
        },
        {
          q: "Can I run more than one assessment?",
          a: "Yes. You can create multiple assessments for different projects and compare the results. Each assessment produces instructions tailored to that specific project.",
        },
        {
          q: "Which AI tools do the generated instructions work with?",
          a: "The generated instructions work with any AI tool that supports a system prompt or custom instructions, including ChatGPT, Claude, Gemini, and others.",
        },
        {
          q: "What's the difference between the full and quick assessments?",
          a: "The quick assessment focuses on 5 dimensions of how you interact with AI and generates instant starter prompts in 5 minutes for free. The full assessment analyzes 7 behavioral axes in depth and produces a comprehensive system prompt with a detailed report.",
        },
      ],
    },
    finalCta: {
      badge: "Start today — no credit card required",
      titleLead: "It's time for",
      titleAccent: "AI to understand you",
      paragraph:
        "The difference between average AI and AI that's truly yours starts with instructions built around who you are — not what you type.",
      primary: "Start free — 5 minutes",
      secondary: "Full assessment — $10",
    },
  },
  i18nDemo: {
    title: "Bilingual foundation verification",
    subtitle:
      "Verification page only: language switching, document direction, and mixed-direction content.",
    currentLocale: "Current locale",
    documentDir: "Document direction",
    fallbackOrder: "Detection order",
    fallbackOrderValue: "?lang= → localStorage → navigator.language → ar",
    switchTo: "Switch to",
    sampleArHeader: "Arabic report inside any UI",
    sampleEnHeader: "English report inside any UI",
    sampleBothHeader: "Bilingual report (vertically stacked)",
    sampleAr:
      "هذا نص تقرير افتراضي بالعربية لاختبار اتجاه RTL داخل بطاقة التقرير. يجب أن يبقى الاتجاه يمين-يسار حتى لو كانت لغة الواجهة الإنجليزية.",
    sampleEn:
      "This is a sample English report body to verify LTR direction inside a report block. It must remain left-to-right even if the surrounding UI is in Arabic.",
    rules: {
      title: "What you should see",
      r1: "?lang=ar activates Arabic and right-to-left direction.",
      r2: "?lang=en activates English and left-to-right direction.",
      r3: "The language choice persists after reload.",
      r4: "The report card preserves its own direction regardless of the UI language.",
      r5: "The 'both' case renders both versions stacked vertically.",
      r6: "The mismatch notice appears subtly when UI and report languages differ.",
    },
  },
};
