import type { Dictionary } from "./ar";

export const en: Dictionary = {
  common: {
    languageSwitcher: {
      ar: "العربية",
      en: "English",
      label: "Language",
    },
    copy: {
      label: "Copy",
      copied: "Copied",
    },
    actions: {
      back: "Back",
      next: "Next",
      close: "Close",
      learnMore: "Learn more",
    },
    direction: {
      isRtl: "Arabic (right-to-left)",
      isLtr: "English (left-to-right)",
    },
  },
  results: {
    pageTitle: "Your assistant operating profile",
    mismatchNotice:
      "The interface language differs from the report language. The report is shown in its original language to preserve its content.",
    dateLocale: "en-US",
    sections: {
      identity: "Assistant identity",
      benefits: "What you gain",
      roles: "Dynamic roles",
      modes: "Thinking modes",
      redLines: "Red lines",
      profile: "Full operating profile",
      howToUse: "How to use it",
      starters: "Starter prompts",
    },
    actions: {
      copyAll: "Copy assistant instructions",
      copySection: "Copy this section",
      share: "Share",
      downloadPdf: "Download PDF",
      openInChatGPT: "Open in ChatGPT",
      openInGemini: "Open in Gemini",
      openInClaude: "Open in Claude",
    },
    platforms: {
      chatgpt: {
        name: "ChatGPT",
        howTo:
          "Open ChatGPT customization settings and paste this profile into the instructions field to activate your assistant's working style.",
        step1: "Open ChatGPT and go to Customize ChatGPT settings.",
        step2:
          'Paste the operating profile into the "How would you like ChatGPT to respond?" field.',
        step3:
          "Save the settings. Your assistant will use this style in every new conversation.",
      },
      gemini: {
        name: "Gemini",
        howTo:
          "Open Gemini Gems or your personal context settings and paste this profile to apply the instructions to your conversations.",
        step1: 'Open Gemini and pick "Gems" to create a new assistant.',
        step2:
          'Paste the operating profile into the Gem instructions field and save it as "Project Assistant".',
        step3: "Open this Gem whenever you need this specific role.",
      },
      claude: {
        name: "Claude",
        howTo:
          "Open Claude Projects, create a new project, then paste this profile into the System Prompt to get the same behavior.",
        step1: "In Claude, create a new Project named after your project.",
        step2:
          "Paste the operating profile into the project's Custom Instructions field.",
        step3:
          "Start every conversation from this project to get the same consistent behavior.",
      },
    },
    starters: {
      eyebrow: "Start now",
      title: "Ready-to-use starter prompts",
      subtitle:
        "Copy any of these and paste it after the operating profile in any new conversation.",
      hint: "Use it directly in your preferred tool.",
    },
    status: {
      ready: "Your operating profile is ready",
      processingTitle: "Analyzing your behavioral profile",
      processingLine1:
        "The AI is generating your customized assistant instructions",
      processingLine2: "This usually takes 30–60 seconds",
      errorTitle: "Couldn't open the report",
      errorMissing: "Report not found",
      errorBack: "Back to my reports",
    },
    header: {
      titlePrefix: "Your assistant operating profile is ready",
      titleConnector: "for",
      subtitle:
        "Use it with ChatGPT, Gemini, or Claude so the AI works with you more clearly and consistently.",
      ctaPrimary: "Copy assistant instructions",
      ctaPrimarySuccess: "All instructions copied",
      ctaSecondary: "How do I use it?",
      generatedBy: "Generated by",
      myAssessments: "My reports",
      downloadPdf: "Download PDF",
      generatePdf: "Generate PDF",
      generatingPdf: "Generating...",
      share: "Share results",
      sharing: "Preparing...",
      revokeShare: "Revoke share",
      revoking: "Revoking...",
      linkCopiedPrefix: "Link copied:",
      shareCancelled: "Share link revoked",
    },
    identity: {
      eyebrow: "Your assistant identity",
      titlePrefix: "Your personal assistant ·",
      fallbackParagraph:
        "A custom operating profile has been built for your project. Use it so the assistant always works in your context instead of giving generic answers.",
      tagPartner: "Execution partner",
      tagReviewer: "Decision reviewer",
      tagContextAware: "Context-aware",
      tagOutcomeFocused: "Outcome-focused",
    },
    strengths: {
      eyebrow: "Your strengths",
      title: "What your assistant does especially well",
      subtitle:
        "These are the strengths the analysis identified in your style.",
    },
    redLines: {
      eyebrow: "Red lines",
      title: "What your assistant should avoid",
      subtitle:
        "Clear boundaries so outputs stay aligned with your style and project requirements.",
    },
    developmentAreas: {
      eyebrow: "Worth your attention",
      title: "Aspects to keep in mind",
      subtitle:
        "Not flaws — just areas worth noticing while working with the assistant.",
    },
    recommendations: {
      eyebrow: "Practical recommendations",
      title: "Steps you can start with",
      subtitle: "Recommendations tied to your style and intended outcomes.",
    },
    profile: {
      eyebrow: "Operating profile",
      title: "Your ready-to-use assistant instructions",
      subtitle:
        "An operating profile written in natural language, ready to paste into ChatGPT, Gemini, or Claude.",
      headerLabel: "Your assistant operating profile",
      headerHint: "Copy the instructions into ChatGPT / Gemini / Claude",
      copyAll: "Copy the full profile",
      copyAllSuccess: "Full profile copied",
    },
    howToUse: {
      eyebrow: "How to use it",
      title: "Where to use the operating profile",
      subtitle:
        "The same profile works across the three major tools. Pick yours and follow the steps.",
      headingPrefix: "How to use it in",
    },
    newCta: {
      line: "Want an operating profile for another project?",
      button: "Start a new assessment",
    },
    projectGoalLabel: "Project goal",
  },
  i18nDemo: {
    title: "Bilingual foundation verification",
    subtitle:
      "Verification page only: language switching, document direction, and mixed-direction content.",
    currentLocale: "Current locale",
    documentDir: "Document direction",
    fallbackOrder: "Detection order",
    fallbackOrderValue: "?lang= → localStorage → navigator.language → ar",
    switchTo: "Switch to",
    sampleArHeader: "Arabic report inside any UI",
    sampleEnHeader: "English report inside any UI",
    sampleBothHeader: "Bilingual report (vertically stacked)",
    sampleAr:
      "هذا نص تقرير افتراضي بالعربية لاختبار اتجاه RTL داخل بطاقة التقرير. يجب أن يبقى الاتجاه يمين-يسار حتى لو كانت لغة الواجهة الإنجليزية.",
    sampleEn:
      "This is a sample English report body to verify LTR direction inside a report block. It must remain left-to-right even if the surrounding UI is in Arabic.",
    rules: {
      title: "What you should see",
      r1: "?lang=ar activates Arabic and right-to-left direction.",
      r2: "?lang=en activates English and left-to-right direction.",
      r3: "The language choice persists after reload.",
      r4: "The report card preserves its own direction regardless of the UI language.",
      r5: "The 'both' case renders both versions stacked vertically.",
      r6: "The mismatch notice appears subtly when UI and report languages differ.",
    },
  },
};
